title: Derecho
description: Distributed systems toolkit for RDMA
google_analytics: 
show_downloads: false
theme: jekyll-theme-time-machine
github.repository_url: https://github.com/Derecho-Project/derecho-unified

gems:
  - jekyll-mentions
